// Code generated by generator.go DO NOT EDIT.
package uigrad

import (
	"github.com/shasderias/ilysa/colorful"
	"github.com/shasderias/ilysa/colorful/gradient"
)

var (
	Omolon = gradient.New(
		colorful.Hex("#091E3A"), colorful.Hex("#2F80ED"), colorful.Hex("#2D9EE0"),
	)

	Farhan = gradient.New(
		colorful.Hex("#9400D3"), colorful.Hex("#4B0082"),
	)

	Purple = gradient.New(
		colorful.Hex("#c84e89"), colorful.Hex("#F15F79"),
	)

	Ibtesam = gradient.New(
		colorful.Hex("#00F5A0"), colorful.Hex("#00D9F5"),
	)

	RadioactiveHeat = gradient.New(
		colorful.Hex("#F7941E"), colorful.Hex("#72C6EF"), colorful.Hex("#00A651"),
	)

	TheSkyAndTheSea = gradient.New(
		colorful.Hex("#F7941E"), colorful.Hex("#004E8F"),
	)

	FromIceToFire = gradient.New(
		colorful.Hex("#72C6EF"), colorful.Hex("#004E8F"),
	)

	BlueAndOrange = gradient.New(
		colorful.Hex("#FD8112"), colorful.Hex("#0085CA"),
	)

	PurpleDream = gradient.New(
		colorful.Hex("#bf5ae0"), colorful.Hex("#a811da"),
	)

	Blu = gradient.New(
		colorful.Hex("#00416A"), colorful.Hex("#E4E5E6"),
	)

	SummerBreeze = gradient.New(
		colorful.Hex("#fbed96"), colorful.Hex("#abecd6"),
	)

	Ver = gradient.New(
		colorful.Hex("#FFE000"), colorful.Hex("#799F0C"),
	)

	VerBlack = gradient.New(
		colorful.Hex("#F7F8F8"), colorful.Hex("#ACBB78"),
	)

	Combi = gradient.New(
		colorful.Hex("#00416A"), colorful.Hex("#799F0C"), colorful.Hex("#FFE000"),
	)

	Anwar = gradient.New(
		colorful.Hex("#334d50"), colorful.Hex("#cbcaa5"),
	)

	Bluelagoo = gradient.New(
		colorful.Hex("#0052D4"), colorful.Hex("#4364F7"), colorful.Hex("#6FB1FC"),
	)

	Lunada = gradient.New(
		colorful.Hex("#5433FF"), colorful.Hex("#20BDFF"), colorful.Hex("#A5FECB"),
	)

	Reaqua = gradient.New(
		colorful.Hex("#799F0C"), colorful.Hex("#ACBB78"),
	)

	Mango = gradient.New(
		colorful.Hex("#ffe259"), colorful.Hex("#ffa751"),
	)

	Bupe = gradient.New(
		colorful.Hex("#00416A"), colorful.Hex("#E4E5E6"),
	)

	Rea = gradient.New(
		colorful.Hex("#FFE000"), colorful.Hex("#799F0C"),
	)

	Windy = gradient.New(
		colorful.Hex("#acb6e5"), colorful.Hex("#86fde8"),
	)

	RoyalBlue = gradient.New(
		colorful.Hex("#536976"), colorful.Hex("#292E49"),
	)

	RoyalBluePlusPetrol = gradient.New(
		colorful.Hex("#BBD2C5"), colorful.Hex("#536976"), colorful.Hex("#292E49"),
	)

	Copper = gradient.New(
		colorful.Hex("#B79891"), colorful.Hex("#94716B"),
	)

	Anamnisar = gradient.New(
		colorful.Hex("#9796f0"), colorful.Hex("#fbc7d4"),
	)

	Petrol = gradient.New(
		colorful.Hex("#BBD2C5"), colorful.Hex("#536976"),
	)

	Sky = gradient.New(
		colorful.Hex("#076585"), colorful.Hex("#fff"),
	)

	Sel = gradient.New(
		colorful.Hex("#00467F"), colorful.Hex("#A5CC82"),
	)

	Afternoon = gradient.New(
		colorful.Hex("#000C40"), colorful.Hex("#607D8B"),
	)

	Skyline = gradient.New(
		colorful.Hex("#1488CC"), colorful.Hex("#2B32B2"),
	)

	DIMIGO = gradient.New(
		colorful.Hex("#ec008c"), colorful.Hex("#fc6767"),
	)

	PurpleLove = gradient.New(
		colorful.Hex("#cc2b5e"), colorful.Hex("#753a88"),
	)

	SexyBlue = gradient.New(
		colorful.Hex("#2193b0"), colorful.Hex("#6dd5ed"),
	)

	Blooker20 = gradient.New(
		colorful.Hex("#e65c00"), colorful.Hex("#F9D423"),
	)

	SeaBlue = gradient.New(
		colorful.Hex("#2b5876"), colorful.Hex("#4e4376"),
	)

	Nimvelo = gradient.New(
		colorful.Hex("#314755"), colorful.Hex("#26a0da"),
	)

	Hazel = gradient.New(
		colorful.Hex("#77A1D3"), colorful.Hex("#79CBCA"), colorful.Hex("#E684AE"),
	)

	NoontoDusk = gradient.New(
		colorful.Hex("#ff6e7f"), colorful.Hex("#bfe9ff"),
	)

	YouTube = gradient.New(
		colorful.Hex("#e52d27"), colorful.Hex("#b31217"),
	)

	CoolBrown = gradient.New(
		colorful.Hex("#603813"), colorful.Hex("#b29f94"),
	)

	HarmonicEnergy = gradient.New(
		colorful.Hex("#16A085"), colorful.Hex("#F4D03F"),
	)

	PlayingwithReds = gradient.New(
		colorful.Hex("#D31027"), colorful.Hex("#EA384D"),
	)

	SunnyDays = gradient.New(
		colorful.Hex("#EDE574"), colorful.Hex("#E1F5C4"),
	)

	GreenBeach = gradient.New(
		colorful.Hex("#02AAB0"), colorful.Hex("#00CDAC"),
	)

	IntuitivePurple = gradient.New(
		colorful.Hex("#DA22FF"), colorful.Hex("#9733EE"),
	)

	EmeraldWater = gradient.New(
		colorful.Hex("#348F50"), colorful.Hex("#56B4D3"),
	)

	LemonTwist = gradient.New(
		colorful.Hex("#3CA55C"), colorful.Hex("#B5AC49"),
	)

	MonteCarlo = gradient.New(
		colorful.Hex("#CC95C0"), colorful.Hex("#DBD4B4"), colorful.Hex("#7AA1D2"),
	)

	Horizon = gradient.New(
		colorful.Hex("#003973"), colorful.Hex("#E5E5BE"),
	)

	RoseWater = gradient.New(
		colorful.Hex("#E55D87"), colorful.Hex("#5FC3E4"),
	)

	Frozen = gradient.New(
		colorful.Hex("#403B4A"), colorful.Hex("#E7E9BB"),
	)

	MangoPulp = gradient.New(
		colorful.Hex("#F09819"), colorful.Hex("#EDDE5D"),
	)

	BloodyMary = gradient.New(
		colorful.Hex("#FF512F"), colorful.Hex("#DD2476"),
	)

	Aubergine = gradient.New(
		colorful.Hex("#AA076B"), colorful.Hex("#61045F"),
	)

	AquaMarine = gradient.New(
		colorful.Hex("#1A2980"), colorful.Hex("#26D0CE"),
	)

	Sunrise = gradient.New(
		colorful.Hex("#FF512F"), colorful.Hex("#F09819"),
	)

	PurpleParadise = gradient.New(
		colorful.Hex("#1D2B64"), colorful.Hex("#F8CDDA"),
	)

	Stripe = gradient.New(
		colorful.Hex("#1FA2FF"), colorful.Hex("#12D8FA"), colorful.Hex("#A6FFCB"),
	)

	SeaWeed = gradient.New(
		colorful.Hex("#4CB8C4"), colorful.Hex("#3CD3AD"),
	)

	Pinky = gradient.New(
		colorful.Hex("#DD5E89"), colorful.Hex("#F7BB97"),
	)

	Cherry = gradient.New(
		colorful.Hex("#EB3349"), colorful.Hex("#F45C43"),
	)

	Mojito = gradient.New(
		colorful.Hex("#1D976C"), colorful.Hex("#93F9B9"),
	)

	JuicyOrange = gradient.New(
		colorful.Hex("#FF8008"), colorful.Hex("#FFC837"),
	)

	Mirage = gradient.New(
		colorful.Hex("#16222A"), colorful.Hex("#3A6073"),
	)

	SteelGray = gradient.New(
		colorful.Hex("#1F1C2C"), colorful.Hex("#928DAB"),
	)

	Kashmir = gradient.New(
		colorful.Hex("#614385"), colorful.Hex("#516395"),
	)

	ElectricViolet = gradient.New(
		colorful.Hex("#4776E6"), colorful.Hex("#8E54E9"),
	)

	VeniceBlue = gradient.New(
		colorful.Hex("#085078"), colorful.Hex("#85D8CE"),
	)

	BoraBora = gradient.New(
		colorful.Hex("#2BC0E4"), colorful.Hex("#EAECC6"),
	)

	Moss = gradient.New(
		colorful.Hex("#134E5E"), colorful.Hex("#71B280"),
	)

	ShroomHaze = gradient.New(
		colorful.Hex("#5C258D"), colorful.Hex("#4389A2"),
	)

	Mystic = gradient.New(
		colorful.Hex("#757F9A"), colorful.Hex("#D7DDE8"),
	)

	MidnightCity = gradient.New(
		colorful.Hex("#232526"), colorful.Hex("#414345"),
	)

	SeaBlizz = gradient.New(
		colorful.Hex("#1CD8D2"), colorful.Hex("#93EDC7"),
	)

	Opa = gradient.New(
		colorful.Hex("#3D7EAA"), colorful.Hex("#FFE47A"),
	)

	Titanium = gradient.New(
		colorful.Hex("#283048"), colorful.Hex("#859398"),
	)

	Mantle = gradient.New(
		colorful.Hex("#24C6DC"), colorful.Hex("#514A9D"),
	)

	Dracula = gradient.New(
		colorful.Hex("#DC2424"), colorful.Hex("#4A569D"),
	)

	Peach = gradient.New(
		colorful.Hex("#ED4264"), colorful.Hex("#FFEDBC"),
	)

	Moonrise = gradient.New(
		colorful.Hex("#DAE2F8"), colorful.Hex("#D6A4A4"),
	)

	Clouds = gradient.New(
		colorful.Hex("#ECE9E6"), colorful.Hex("#FFFFFF"),
	)

	Stellar = gradient.New(
		colorful.Hex("#7474BF"), colorful.Hex("#348AC7"),
	)

	Bourbon = gradient.New(
		colorful.Hex("#EC6F66"), colorful.Hex("#F3A183"),
	)

	CalmDarya = gradient.New(
		colorful.Hex("#5f2c82"), colorful.Hex("#49a09d"),
	)

	Influenza = gradient.New(
		colorful.Hex("#C04848"), colorful.Hex("#480048"),
	)

	Shrimpy = gradient.New(
		colorful.Hex("#e43a15"), colorful.Hex("#e65245"),
	)

	Army = gradient.New(
		colorful.Hex("#414d0b"), colorful.Hex("#727a17"),
	)

	Miaka = gradient.New(
		colorful.Hex("#FC354C"), colorful.Hex("#0ABFBC"),
	)

	PinotNoir = gradient.New(
		colorful.Hex("#4b6cb7"), colorful.Hex("#182848"),
	)

	DayTripper = gradient.New(
		colorful.Hex("#f857a6"), colorful.Hex("#ff5858"),
	)

	Namn = gradient.New(
		colorful.Hex("#a73737"), colorful.Hex("#7a2828"),
	)

	BlurryBeach = gradient.New(
		colorful.Hex("#d53369"), colorful.Hex("#cbad6d"),
	)

	Vasily = gradient.New(
		colorful.Hex("#e9d362"), colorful.Hex("#333333"),
	)

	ALostMemory = gradient.New(
		colorful.Hex("#DE6262"), colorful.Hex("#FFB88C"),
	)

	Petrichor = gradient.New(
		colorful.Hex("#666600"), colorful.Hex("#999966"),
	)

	Jonquil = gradient.New(
		colorful.Hex("#FFEEEE"), colorful.Hex("#DDEFBB"),
	)

	SiriusTamed = gradient.New(
		colorful.Hex("#EFEFBB"), colorful.Hex("#D4D3DD"),
	)

	Kyoto = gradient.New(
		colorful.Hex("#c21500"), colorful.Hex("#ffc500"),
	)

	MistyMeadow = gradient.New(
		colorful.Hex("#215f00"), colorful.Hex("#e4e4d9"),
	)

	Aqualicious = gradient.New(
		colorful.Hex("#50C9C3"), colorful.Hex("#96DEDA"),
	)

	Moor = gradient.New(
		colorful.Hex("#616161"), colorful.Hex("#9bc5c3"),
	)

	Almost = gradient.New(
		colorful.Hex("#ddd6f3"), colorful.Hex("#faaca8"),
	)

	ForeverLost = gradient.New(
		colorful.Hex("#5D4157"), colorful.Hex("#A8CABA"),
	)

	Winter = gradient.New(
		colorful.Hex("#E6DADA"), colorful.Hex("#274046"),
	)

	Nelson = gradient.New(
		colorful.Hex("#f2709c"), colorful.Hex("#ff9472"),
	)

	Autumn = gradient.New(
		colorful.Hex("#DAD299"), colorful.Hex("#B0DAB9"),
	)

	Candy = gradient.New(
		colorful.Hex("#D3959B"), colorful.Hex("#BFE6BA"),
	)

	Reef = gradient.New(
		colorful.Hex("#00d2ff"), colorful.Hex("#3a7bd5"),
	)

	TheStrain = gradient.New(
		colorful.Hex("#870000"), colorful.Hex("#190A05"),
	)

	DirtyFog = gradient.New(
		colorful.Hex("#B993D6"), colorful.Hex("#8CA6DB"),
	)

	Earthly = gradient.New(
		colorful.Hex("#649173"), colorful.Hex("#DBD5A4"),
	)

	Virgin = gradient.New(
		colorful.Hex("#C9FFBF"), colorful.Hex("#FFAFBD"),
	)

	Ash = gradient.New(
		colorful.Hex("#606c88"), colorful.Hex("#3f4c6b"),
	)

	Cherryblossoms = gradient.New(
		colorful.Hex("#FBD3E9"), colorful.Hex("#BB377D"),
	)

	Parklife = gradient.New(
		colorful.Hex("#ADD100"), colorful.Hex("#7B920A"),
	)

	DanceToForget = gradient.New(
		colorful.Hex("#FF4E50"), colorful.Hex("#F9D423"),
	)

	Starfall = gradient.New(
		colorful.Hex("#F0C27B"), colorful.Hex("#4B1248"),
	)

	RedMist = gradient.New(
		colorful.Hex("#000000"), colorful.Hex("#e74c3c"),
	)

	TealLove = gradient.New(
		colorful.Hex("#AAFFA9"), colorful.Hex("#11FFBD"),
	)

	NeonLife = gradient.New(
		colorful.Hex("#B3FFAB"), colorful.Hex("#12FFF7"),
	)

	ManofSteel = gradient.New(
		colorful.Hex("#780206"), colorful.Hex("#061161"),
	)

	Amethyst = gradient.New(
		colorful.Hex("#9D50BB"), colorful.Hex("#6E48AA"),
	)

	CheerUpEmoKid = gradient.New(
		colorful.Hex("#556270"), colorful.Hex("#FF6B6B"),
	)

	Shore = gradient.New(
		colorful.Hex("#70e1f5"), colorful.Hex("#ffd194"),
	)

	FacebookMessenger = gradient.New(
		colorful.Hex("#00c6ff"), colorful.Hex("#0072ff"),
	)

	SoundCloud = gradient.New(
		colorful.Hex("#fe8c00"), colorful.Hex("#f83600"),
	)

	Behongo = gradient.New(
		colorful.Hex("#52c234"), colorful.Hex("#061700"),
	)

	ServQuick = gradient.New(
		colorful.Hex("#485563"), colorful.Hex("#29323c"),
	)

	Friday = gradient.New(
		colorful.Hex("#83a4d4"), colorful.Hex("#b6fbff"),
	)

	Martini = gradient.New(
		colorful.Hex("#FDFC47"), colorful.Hex("#24FE41"),
	)

	MetallicToad = gradient.New(
		colorful.Hex("#abbaab"), colorful.Hex("#ffffff"),
	)

	BetweenTheClouds = gradient.New(
		colorful.Hex("#73C8A9"), colorful.Hex("#373B44"),
	)

	CrazyOrangeI = gradient.New(
		colorful.Hex("#D38312"), colorful.Hex("#A83279"),
	)

	Hersheys = gradient.New(
		colorful.Hex("#1e130c"), colorful.Hex("#9a8478"),
	)

	TalkingToMiceElf = gradient.New(
		colorful.Hex("#948E99"), colorful.Hex("#2E1437"),
	)

	PurpleBliss = gradient.New(
		colorful.Hex("#360033"), colorful.Hex("#0b8793"),
	)

	Predawn = gradient.New(
		colorful.Hex("#FFA17F"), colorful.Hex("#00223E"),
	)

	EndlessRiver = gradient.New(
		colorful.Hex("#43cea2"), colorful.Hex("#185a9d"),
	)

	PastelOrangeattheSun = gradient.New(
		colorful.Hex("#ffb347"), colorful.Hex("#ffcc33"),
	)

	Twitch = gradient.New(
		colorful.Hex("#6441A5"), colorful.Hex("#2a0845"),
	)

	Atlas = gradient.New(
		colorful.Hex("#FEAC5E"), colorful.Hex("#C779D0"), colorful.Hex("#4BC0C8"),
	)

	Instagram = gradient.New(
		colorful.Hex("#833ab4"), colorful.Hex("#fd1d1d"), colorful.Hex("#fcb045"),
	)

	Flickr = gradient.New(
		colorful.Hex("#ff0084"), colorful.Hex("#33001b"),
	)

	Vine = gradient.New(
		colorful.Hex("#00bf8f"), colorful.Hex("#001510"),
	)

	Turquoiseflow = gradient.New(
		colorful.Hex("#136a8a"), colorful.Hex("#267871"),
	)

	Portrait = gradient.New(
		colorful.Hex("#8e9eab"), colorful.Hex("#eef2f3"),
	)

	VirginAmerica = gradient.New(
		colorful.Hex("#7b4397"), colorful.Hex("#dc2430"),
	)

	KokoCaramel = gradient.New(
		colorful.Hex("#D1913C"), colorful.Hex("#FFD194"),
	)

	FreshTurboscent = gradient.New(
		colorful.Hex("#F1F2B5"), colorful.Hex("#135058"),
	)

	Greentodark = gradient.New(
		colorful.Hex("#6A9113"), colorful.Hex("#141517"),
	)

	Ukraine = gradient.New(
		colorful.Hex("#004FF9"), colorful.Hex("#FFF94C"),
	)

	Curiosityblue = gradient.New(
		colorful.Hex("#525252"), colorful.Hex("#3d72b4"),
	)

	DarkKnight = gradient.New(
		colorful.Hex("#BA8B02"), colorful.Hex("#181818"),
	)

	Piglet = gradient.New(
		colorful.Hex("#ee9ca7"), colorful.Hex("#ffdde1"),
	)

	Lizard = gradient.New(
		colorful.Hex("#304352"), colorful.Hex("#d7d2cc"),
	)

	SagePersuasion = gradient.New(
		colorful.Hex("#CCCCB2"), colorful.Hex("#757519"),
	)

	BetweenNightandDay = gradient.New(
		colorful.Hex("#2c3e50"), colorful.Hex("#3498db"),
	)

	Timber = gradient.New(
		colorful.Hex("#fc00ff"), colorful.Hex("#00dbde"),
	)

	Passion = gradient.New(
		colorful.Hex("#e53935"), colorful.Hex("#e35d5b"),
	)

	ClearSky = gradient.New(
		colorful.Hex("#005C97"), colorful.Hex("#363795"),
	)

	MasterCard = gradient.New(
		colorful.Hex("#f46b45"), colorful.Hex("#eea849"),
	)

	BackToEarth = gradient.New(
		colorful.Hex("#00C9FF"), colorful.Hex("#92FE9D"),
	)

	DeepPurple = gradient.New(
		colorful.Hex("#673AB7"), colorful.Hex("#512DA8"),
	)

	LittleLeaf = gradient.New(
		colorful.Hex("#76b852"), colorful.Hex("#8DC26F"),
	)

	Netflix = gradient.New(
		colorful.Hex("#8E0E00"), colorful.Hex("#1F1C18"),
	)

	LightOrange = gradient.New(
		colorful.Hex("#FFB75E"), colorful.Hex("#ED8F03"),
	)

	GreenandBlue = gradient.New(
		colorful.Hex("#c2e59c"), colorful.Hex("#64b3f4"),
	)

	Poncho = gradient.New(
		colorful.Hex("#403A3E"), colorful.Hex("#BE5869"),
	)

	BacktotheFuture = gradient.New(
		colorful.Hex("#C02425"), colorful.Hex("#F0CB35"),
	)

	Blush = gradient.New(
		colorful.Hex("#B24592"), colorful.Hex("#F15F79"),
	)

	Inbox = gradient.New(
		colorful.Hex("#457fca"), colorful.Hex("#5691c8"),
	)

	Purplin = gradient.New(
		colorful.Hex("#6a3093"), colorful.Hex("#a044ff"),
	)

	PaleWood = gradient.New(
		colorful.Hex("#eacda3"), colorful.Hex("#d6ae7b"),
	)

	Haikus = gradient.New(
		colorful.Hex("#fd746c"), colorful.Hex("#ff9068"),
	)

	Pizelex = gradient.New(
		colorful.Hex("#114357"), colorful.Hex("#F29492"),
	)

	Joomla = gradient.New(
		colorful.Hex("#1e3c72"), colorful.Hex("#2a5298"),
	)

	Christmas = gradient.New(
		colorful.Hex("#2F7336"), colorful.Hex("#AA3A38"),
	)

	MinnesotaVikings = gradient.New(
		colorful.Hex("#5614B0"), colorful.Hex("#DBD65C"),
	)

	MiamiDolphins = gradient.New(
		colorful.Hex("#4DA0B0"), colorful.Hex("#D39D38"),
	)

	Forest = gradient.New(
		colorful.Hex("#5A3F37"), colorful.Hex("#2C7744"),
	)

	Nighthawk = gradient.New(
		colorful.Hex("#2980b9"), colorful.Hex("#2c3e50"),
	)

	Superman = gradient.New(
		colorful.Hex("#0099F7"), colorful.Hex("#F11712"),
	)

	Suzy = gradient.New(
		colorful.Hex("#834d9b"), colorful.Hex("#d04ed6"),
	)

	DarkSkies = gradient.New(
		colorful.Hex("#4B79A1"), colorful.Hex("#283E51"),
	)

	DeepSpace = gradient.New(
		colorful.Hex("#000000"), colorful.Hex("#434343"),
	)

	Decent = gradient.New(
		colorful.Hex("#4CA1AF"), colorful.Hex("#C4E0E5"),
	)

	ColorsOfSky = gradient.New(
		colorful.Hex("#E0EAFC"), colorful.Hex("#CFDEF3"),
	)

	PurpleWhite = gradient.New(
		colorful.Hex("#BA5370"), colorful.Hex("#F4E2D8"),
	)

	Ali = gradient.New(
		colorful.Hex("#ff4b1f"), colorful.Hex("#1fddff"),
	)

	Alihossein = gradient.New(
		colorful.Hex("#f7ff00"), colorful.Hex("#db36a4"),
	)

	Shahabi = gradient.New(
		colorful.Hex("#a80077"), colorful.Hex("#66ff00"),
	)

	RedOcean = gradient.New(
		colorful.Hex("#1D4350"), colorful.Hex("#A43931"),
	)

	Tranquil = gradient.New(
		colorful.Hex("#EECDA3"), colorful.Hex("#EF629F"),
	)

	Transfile = gradient.New(
		colorful.Hex("#16BFFD"), colorful.Hex("#CB3066"),
	)

	Sylvia = gradient.New(
		colorful.Hex("#ff4b1f"), colorful.Hex("#ff9068"),
	)

	SweetMorning = gradient.New(
		colorful.Hex("#FF5F6D"), colorful.Hex("#FFC371"),
	)

	Politics = gradient.New(
		colorful.Hex("#2196f3"), colorful.Hex("#f44336"),
	)

	BrightVault = gradient.New(
		colorful.Hex("#00d2ff"), colorful.Hex("#928DAB"),
	)

	SolidVault = gradient.New(
		colorful.Hex("#3a7bd5"), colorful.Hex("#3a6073"),
	)

	Sunset = gradient.New(
		colorful.Hex("#0B486B"), colorful.Hex("#F56217"),
	)

	GrapefruitSunset = gradient.New(
		colorful.Hex("#e96443"), colorful.Hex("#904e95"),
	)

	DeepSeaSpace = gradient.New(
		colorful.Hex("#2C3E50"), colorful.Hex("#4CA1AF"),
	)

	Dusk = gradient.New(
		colorful.Hex("#2C3E50"), colorful.Hex("#FD746C"),
	)

	MinimalRed = gradient.New(
		colorful.Hex("#F00000"), colorful.Hex("#DC281E"),
	)

	Royal = gradient.New(
		colorful.Hex("#141E30"), colorful.Hex("#243B55"),
	)

	Mauve = gradient.New(
		colorful.Hex("#42275a"), colorful.Hex("#734b6d"),
	)

	Frost = gradient.New(
		colorful.Hex("#000428"), colorful.Hex("#004e92"),
	)

	Lush = gradient.New(
		colorful.Hex("#56ab2f"), colorful.Hex("#a8e063"),
	)

	Firewatch = gradient.New(
		colorful.Hex("#cb2d3e"), colorful.Hex("#ef473a"),
	)

	Sherbert = gradient.New(
		colorful.Hex("#f79d00"), colorful.Hex("#64f38c"),
	)

	BloodRed = gradient.New(
		colorful.Hex("#f85032"), colorful.Hex("#e73827"),
	)

	SunontheHorizon = gradient.New(
		colorful.Hex("#fceabb"), colorful.Hex("#f8b500"),
	)

	IIITDelhi = gradient.New(
		colorful.Hex("#808080"), colorful.Hex("#3fada8"),
	)

	Jupiter = gradient.New(
		colorful.Hex("#ffd89b"), colorful.Hex("#19547b"),
	)

	FiftyShadesofGrey = gradient.New(
		colorful.Hex("#bdc3c7"), colorful.Hex("#2c3e50"),
	)

	Dania = gradient.New(
		colorful.Hex("#BE93C5"), colorful.Hex("#7BC6CC"),
	)

	Limeade = gradient.New(
		colorful.Hex("#A1FFCE"), colorful.Hex("#FAFFD1"),
	)

	Disco = gradient.New(
		colorful.Hex("#4ECDC4"), colorful.Hex("#556270"),
	)

	LoveCouple = gradient.New(
		colorful.Hex("#3a6186"), colorful.Hex("#89253e"),
	)

	AzurePop = gradient.New(
		colorful.Hex("#ef32d9"), colorful.Hex("#89fffd"),
	)

	Nepal = gradient.New(
		colorful.Hex("#de6161"), colorful.Hex("#2657eb"),
	)

	CosmicFusion = gradient.New(
		colorful.Hex("#ff00cc"), colorful.Hex("#333399"),
	)

	Snapchat = gradient.New(
		colorful.Hex("#fffc00"), colorful.Hex("#ffffff"),
	)

	EdsSunsetGradient = gradient.New(
		colorful.Hex("#ff7e5f"), colorful.Hex("#feb47b"),
	)

	BradyBradyFunFun = gradient.New(
		colorful.Hex("#00c3ff"), colorful.Hex("#ffff1c"),
	)

	BlackRosé = gradient.New(
		colorful.Hex("#f4c4f3"), colorful.Hex("#fc67fa"),
	)

	EightiessPurple = gradient.New(
		colorful.Hex("#41295a"), colorful.Hex("#2F0743"),
	)

	Radar = gradient.New(
		colorful.Hex("#A770EF"), colorful.Hex("#CF8BF3"), colorful.Hex("#FDB99B"),
	)

	IbizaSunset = gradient.New(
		colorful.Hex("#ee0979"), colorful.Hex("#ff6a00"),
	)

	Dawn = gradient.New(
		colorful.Hex("#F3904F"), colorful.Hex("#3B4371"),
	)

	Mild = gradient.New(
		colorful.Hex("#67B26F"), colorful.Hex("#4ca2cd"),
	)

	ViceCity = gradient.New(
		colorful.Hex("#3494E6"), colorful.Hex("#EC6EAD"),
	)

	Jaipur = gradient.New(
		colorful.Hex("#DBE6F6"), colorful.Hex("#C5796D"),
	)

	Jodhpur = gradient.New(
		colorful.Hex("#9CECFB"), colorful.Hex("#65C7F7"), colorful.Hex("#0052D4"),
	)

	CocoaaIce = gradient.New(
		colorful.Hex("#c0c0aa"), colorful.Hex("#1cefff"),
	)

	EasyMed = gradient.New(
		colorful.Hex("#DCE35B"), colorful.Hex("#45B649"),
	)

	RoseColoredLenses = gradient.New(
		colorful.Hex("#E8CBC0"), colorful.Hex("#636FA4"),
	)

	WhatliesBeyond = gradient.New(
		colorful.Hex("#F0F2F0"), colorful.Hex("#000C40"),
	)

	Roseanna = gradient.New(
		colorful.Hex("#FFAFBD"), colorful.Hex("#ffc3a0"),
	)

	HoneyDew = gradient.New(
		colorful.Hex("#43C6AC"), colorful.Hex("#F8FFAE"),
	)

	UndertheLake = gradient.New(
		colorful.Hex("#093028"), colorful.Hex("#237A57"),
	)

	TheBlueLagoon = gradient.New(
		colorful.Hex("#43C6AC"), colorful.Hex("#191654"),
	)

	CanYouFeelTheLoveTonight = gradient.New(
		colorful.Hex("#4568DC"), colorful.Hex("#B06AB3"),
	)

	VeryBlue = gradient.New(
		colorful.Hex("#0575E6"), colorful.Hex("#021B79"),
	)

	LoveandLiberty = gradient.New(
		colorful.Hex("#200122"), colorful.Hex("#6f0000"),
	)

	Orca = gradient.New(
		colorful.Hex("#44A08D"), colorful.Hex("#093637"),
	)

	Venice = gradient.New(
		colorful.Hex("#6190E8"), colorful.Hex("#A7BFE8"),
	)

	PacificDream = gradient.New(
		colorful.Hex("#34e89e"), colorful.Hex("#0f3443"),
	)

	LearningandLeading = gradient.New(
		colorful.Hex("#F7971E"), colorful.Hex("#FFD200"),
	)

	Celestial = gradient.New(
		colorful.Hex("#C33764"), colorful.Hex("#1D2671"),
	)

	Purplepine = gradient.New(
		colorful.Hex("#20002c"), colorful.Hex("#cbb4d4"),
	)

	Shalala = gradient.New(
		colorful.Hex("#D66D75"), colorful.Hex("#E29587"),
	)

	Mini = gradient.New(
		colorful.Hex("#30E8BF"), colorful.Hex("#FF8235"),
	)

	Maldives = gradient.New(
		colorful.Hex("#B2FEFA"), colorful.Hex("#0ED2F7"),
	)

	Cinnamint = gradient.New(
		colorful.Hex("#4AC29A"), colorful.Hex("#BDFFF3"),
	)

	Html = gradient.New(
		colorful.Hex("#E44D26"), colorful.Hex("#F16529"),
	)

	Coal = gradient.New(
		colorful.Hex("#EB5757"), colorful.Hex("#000000"),
	)

	Sunkist = gradient.New(
		colorful.Hex("#F2994A"), colorful.Hex("#F2C94C"),
	)

	BlueSkies = gradient.New(
		colorful.Hex("#56CCF2"), colorful.Hex("#2F80ED"),
	)

	ChittyChittyBangBang = gradient.New(
		colorful.Hex("#007991"), colorful.Hex("#78ffd6"),
	)

	VisionsofGrandeur = gradient.New(
		colorful.Hex("#000046"), colorful.Hex("#1CB5E0"),
	)

	CrystalClear = gradient.New(
		colorful.Hex("#159957"), colorful.Hex("#155799"),
	)

	Mello = gradient.New(
		colorful.Hex("#c0392b"), colorful.Hex("#8e44ad"),
	)

	CompareNow = gradient.New(
		colorful.Hex("#EF3B36"), colorful.Hex("#FFFFFF"),
	)

	Meridian = gradient.New(
		colorful.Hex("#283c86"), colorful.Hex("#45a247"),
	)

	Relay = gradient.New(
		colorful.Hex("#3A1C71"), colorful.Hex("#D76D77"), colorful.Hex("#FFAF7B"),
	)

	Alive = gradient.New(
		colorful.Hex("#CB356B"), colorful.Hex("#BD3F32"),
	)

	Scooter = gradient.New(
		colorful.Hex("#36D1DC"), colorful.Hex("#5B86E5"),
	)

	Terminal = gradient.New(
		colorful.Hex("#000000"), colorful.Hex("#0f9b0f"),
	)

	Telegram = gradient.New(
		colorful.Hex("#1c92d2"), colorful.Hex("#f2fcfe"),
	)

	CrimsonTide = gradient.New(
		colorful.Hex("#642B73"), colorful.Hex("#C6426E"),
	)

	Socialive = gradient.New(
		colorful.Hex("#06beb6"), colorful.Hex("#48b1bf"),
	)

	Subu = gradient.New(
		colorful.Hex("#0cebeb"), colorful.Hex("#20e3b2"), colorful.Hex("#29ffc6"),
	)

	BrokenHearts = gradient.New(
		colorful.Hex("#d9a7c7"), colorful.Hex("#fffcdc"),
	)

	KimobyIsTheNewBlue = gradient.New(
		colorful.Hex("#396afc"), colorful.Hex("#2948ff"),
	)

	Dull = gradient.New(
		colorful.Hex("#C9D6FF"), colorful.Hex("#E2E2E2"),
	)

	Purpink = gradient.New(
		colorful.Hex("#7F00FF"), colorful.Hex("#E100FF"),
	)

	OrangeCoral = gradient.New(
		colorful.Hex("#ff9966"), colorful.Hex("#ff5e62"),
	)

	Summer = gradient.New(
		colorful.Hex("#22c1c3"), colorful.Hex("#fdbb2d"),
	)

	KingYna = gradient.New(
		colorful.Hex("#1a2a6c"), colorful.Hex("#b21f1f"), colorful.Hex("#fdbb2d"),
	)

	VelvetSun = gradient.New(
		colorful.Hex("#e1eec3"), colorful.Hex("#f05053"),
	)

	Zinc = gradient.New(
		colorful.Hex("#ADA996"), colorful.Hex("#F2F2F2"), colorful.Hex("#DBDBDB"), colorful.Hex("#EAEAEA"),
	)

	Hydrogen = gradient.New(
		colorful.Hex("#667db6"), colorful.Hex("#0082c8"), colorful.Hex("#0082c8"), colorful.Hex("#667db6"),
	)

	Argon = gradient.New(
		colorful.Hex("#03001e"), colorful.Hex("#7303c0"), colorful.Hex("#ec38bc"), colorful.Hex("#fdeff9"),
	)

	Lithium = gradient.New(
		colorful.Hex("#6D6027"), colorful.Hex("#D3CBB8"),
	)

	DigitalWater = gradient.New(
		colorful.Hex("#74ebd5"), colorful.Hex("#ACB6E5"),
	)

	OrangeFun = gradient.New(
		colorful.Hex("#fc4a1a"), colorful.Hex("#f7b733"),
	)

	RainbowBlue = gradient.New(
		colorful.Hex("#00F260"), colorful.Hex("#0575E6"),
	)

	PinkFlavour = gradient.New(
		colorful.Hex("#800080"), colorful.Hex("#ffc0cb"),
	)

	Sulphur = gradient.New(
		colorful.Hex("#CAC531"), colorful.Hex("#F3F9A7"),
	)

	Selenium = gradient.New(
		colorful.Hex("#3C3B3F"), colorful.Hex("#605C3C"),
	)

	Delicate = gradient.New(
		colorful.Hex("#D3CCE3"), colorful.Hex("#E9E4F0"),
	)

	Ohhappiness = gradient.New(
		colorful.Hex("#00b09b"), colorful.Hex("#96c93d"),
	)

	Lawrencium = gradient.New(
		colorful.Hex("#0f0c29"), colorful.Hex("#302b63"), colorful.Hex("#24243e"),
	)

	Relaxingred = gradient.New(
		colorful.Hex("#fffbd5"), colorful.Hex("#b20a2c"),
	)

	TaranTado = gradient.New(
		colorful.Hex("#23074d"), colorful.Hex("#cc5333"),
	)

	Bighead = gradient.New(
		colorful.Hex("#c94b4b"), colorful.Hex("#4b134f"),
	)

	SublimeVivid = gradient.New(
		colorful.Hex("#FC466B"), colorful.Hex("#3F5EFB"),
	)

	SublimeLight = gradient.New(
		colorful.Hex("#FC5C7D"), colorful.Hex("#6A82FB"),
	)

	PunYeta = gradient.New(
		colorful.Hex("#108dc7"), colorful.Hex("#ef8e38"),
	)

	Quepal = gradient.New(
		colorful.Hex("#11998e"), colorful.Hex("#38ef7d"),
	)

	SandtoBlue = gradient.New(
		colorful.Hex("#3E5151"), colorful.Hex("#DECBA4"),
	)

	WeddingDayBlues = gradient.New(
		colorful.Hex("#40E0D0"), colorful.Hex("#FF8C00"), colorful.Hex("#FF0080"),
	)

	Shifter = gradient.New(
		colorful.Hex("#bc4e9c"), colorful.Hex("#f80759"),
	)

	RedSunset = gradient.New(
		colorful.Hex("#355C7D"), colorful.Hex("#6C5B7B"), colorful.Hex("#C06C84"),
	)

	MoonPurple = gradient.New(
		colorful.Hex("#4e54c8"), colorful.Hex("#8f94fb"),
	)

	PureLust = gradient.New(
		colorful.Hex("#333333"), colorful.Hex("#dd1818"),
	)

	SlightOceanView = gradient.New(
		colorful.Hex("#a8c0ff"), colorful.Hex("#3f2b96"),
	)

	eXpresso = gradient.New(
		colorful.Hex("#ad5389"), colorful.Hex("#3c1053"),
	)

	Shifty = gradient.New(
		colorful.Hex("#636363"), colorful.Hex("#a2ab58"),
	)

	Vanusa = gradient.New(
		colorful.Hex("#DA4453"), colorful.Hex("#89216B"),
	)

	EveningNight = gradient.New(
		colorful.Hex("#005AA7"), colorful.Hex("#FFFDE4"),
	)

	Magic = gradient.New(
		colorful.Hex("#59C173"), colorful.Hex("#a17fe0"), colorful.Hex("#5D26C1"),
	)

	Margo = gradient.New(
		colorful.Hex("#FFEFBA"), colorful.Hex("#FFFFFF"),
	)

	BlueRaspberry = gradient.New(
		colorful.Hex("#00B4DB"), colorful.Hex("#0083B0"),
	)

	CitrusPeel = gradient.New(
		colorful.Hex("#FDC830"), colorful.Hex("#F37335"),
	)

	SinCityRed = gradient.New(
		colorful.Hex("#ED213A"), colorful.Hex("#93291E"),
	)

	Rastafari = gradient.New(
		colorful.Hex("#1E9600"), colorful.Hex("#FFF200"), colorful.Hex("#FF0000"),
	)

	SummerDog = gradient.New(
		colorful.Hex("#a8ff78"), colorful.Hex("#78ffd6"),
	)

	Wiretap = gradient.New(
		colorful.Hex("#8A2387"), colorful.Hex("#E94057"), colorful.Hex("#F27121"),
	)

	BurningOrange = gradient.New(
		colorful.Hex("#FF416C"), colorful.Hex("#FF4B2B"),
	)

	UltraVoilet = gradient.New(
		colorful.Hex("#654ea3"), colorful.Hex("#eaafc8"),
	)

	ByDesign = gradient.New(
		colorful.Hex("#009FFF"), colorful.Hex("#ec2F4B"),
	)

	KyooTah = gradient.New(
		colorful.Hex("#544a7d"), colorful.Hex("#ffd452"),
	)

	KyeMeh = gradient.New(
		colorful.Hex("#8360c3"), colorful.Hex("#2ebf91"),
	)

	KyooPal = gradient.New(
		colorful.Hex("#dd3e54"), colorful.Hex("#6be585"),
	)

	Metapolis = gradient.New(
		colorful.Hex("#659999"), colorful.Hex("#f4791f"),
	)

	Flare = gradient.New(
		colorful.Hex("#f12711"), colorful.Hex("#f5af19"),
	)

	WitchingHour = gradient.New(
		colorful.Hex("#c31432"), colorful.Hex("#240b36"),
	)

	AzurLane = gradient.New(
		colorful.Hex("#7F7FD5"), colorful.Hex("#86A8E7"), colorful.Hex("#91EAE4"),
	)

	Neuromancer = gradient.New(
		colorful.Hex("#f953c6"), colorful.Hex("#b91d73"),
	)

	Harvey = gradient.New(
		colorful.Hex("#1f4037"), colorful.Hex("#99f2c8"),
	)

	Amin = gradient.New(
		colorful.Hex("#8E2DE2"), colorful.Hex("#4A00E0"),
	)

	Memariani = gradient.New(
		colorful.Hex("#aa4b6b"), colorful.Hex("#6b6b83"), colorful.Hex("#3b8d99"),
	)

	Yoda = gradient.New(
		colorful.Hex("#FF0099"), colorful.Hex("#493240"),
	)

	CoolSky = gradient.New(
		colorful.Hex("#2980B9"), colorful.Hex("#6DD5FA"), colorful.Hex("#FFFFFF"),
	)

	DarkOcean = gradient.New(
		colorful.Hex("#373B44"), colorful.Hex("#4286f4"),
	)

	EveningSunshine = gradient.New(
		colorful.Hex("#b92b27"), colorful.Hex("#1565C0"),
	)

	JShine = gradient.New(
		colorful.Hex("#12c2e9"), colorful.Hex("#c471ed"), colorful.Hex("#f64f59"),
	)

	MoonlitAsteroid = gradient.New(
		colorful.Hex("#0F2027"), colorful.Hex("#203A43"), colorful.Hex("#2C5364"),
	)

	MegaTron = gradient.New(
		colorful.Hex("#C6FFDD"), colorful.Hex("#FBD786"), colorful.Hex("#f7797d"),
	)

	CoolBlues = gradient.New(
		colorful.Hex("#2193b0"), colorful.Hex("#6dd5ed"),
	)

	PiggyPink = gradient.New(
		colorful.Hex("#ee9ca7"), colorful.Hex("#ffdde1"),
	)

	GradeGrey = gradient.New(
		colorful.Hex("#bdc3c7"), colorful.Hex("#2c3e50"),
	)

	Telko = gradient.New(
		colorful.Hex("#F36222"), colorful.Hex("#5CB644"), colorful.Hex("#007FC3"),
	)

	Zenta = gradient.New(
		colorful.Hex("#2A2D3E"), colorful.Hex("#FECB6E"),
	)

	ElectricPeacock = gradient.New(
		colorful.Hex("#8a2be2"), colorful.Hex("#0000cd"), colorful.Hex("#228b22"), colorful.Hex("#ccff00"),
	)

	UnderBlueGreen = gradient.New(
		colorful.Hex("#051937"), colorful.Hex("#004d7a"), colorful.Hex("#008793"), colorful.Hex("#00bf72"), colorful.Hex("#a8eb12"),
	)

	Lensod = gradient.New(
		colorful.Hex("#6025F5"), colorful.Hex("#FF5555"),
	)

	Newspaper = gradient.New(
		colorful.Hex("#8a2be2"), colorful.Hex("#ffa500"), colorful.Hex("#f8f8ff"),
	)

	DarkBlueGradient = gradient.New(
		colorful.Hex("#2774ae"), colorful.Hex("#002E5D"), colorful.Hex("#002E5D"),
	)

	DarkBluTwo = gradient.New(
		colorful.Hex("#004680"), colorful.Hex("#4484BA"),
	)

	LemonLime = gradient.New(
		colorful.Hex("#7ec6bc"), colorful.Hex("#ebe717"),
	)

	Beleko = gradient.New(
		colorful.Hex("#ff1e56"), colorful.Hex("#f9c942"), colorful.Hex("#1e90ff"),
	)

	MangoPapaya = gradient.New(
		colorful.Hex("#de8a41"), colorful.Hex("#2ada53"),
	)

	UnicornRainbow = gradient.New(
		colorful.Hex("#f7f0ac"), colorful.Hex("#acf7f0"), colorful.Hex("#f0acf7"),
	)

	Flame = gradient.New(
		colorful.Hex("#ff0000"), colorful.Hex("#fdcf58"),
	)

	BlueRed = gradient.New(
		colorful.Hex("#36B1C7"), colorful.Hex("#960B33"),
	)

	Twitter = gradient.New(
		colorful.Hex("#1DA1F2"), colorful.Hex("#009ffc"),
	)

	Blooze = gradient.New(
		colorful.Hex("#6da6be"), colorful.Hex("#4b859e"), colorful.Hex("#6da6be"),
	)

	BlueSlate = gradient.New(
		colorful.Hex("#B5B9FF"), colorful.Hex("#2B2C49"),
	)

	SpaceLightGreen = gradient.New(
		colorful.Hex("#9FA0A8"), colorful.Hex("#5C7852"),
	)

	Flower = gradient.New(
		colorful.Hex("#DCFFBD"), colorful.Hex("#CC86D1"),
	)

	ElateTheEuge = gradient.New(
		colorful.Hex("#8BDEDA"), colorful.Hex("#43ADD0"), colorful.Hex("#998EE0"), colorful.Hex("#E17DC2"), colorful.Hex("#EF9393"),
	)

	PeachSea = gradient.New(
		colorful.Hex("#E6AE8C"), colorful.Hex("#A8CECF"),
	)

	Abbas = gradient.New(
		colorful.Hex("#00fff0"), colorful.Hex("#0083fe"),
	)

	WinterWoods = gradient.New(
		colorful.Hex("#333333"), colorful.Hex("#a2ab58"), colorful.Hex("#A43931"),
	)

	Ameena = gradient.New(
		colorful.Hex("#0c0c6d"), colorful.Hex("#de512b"), colorful.Hex("#98d0c1"), colorful.Hex("#5bb226"), colorful.Hex("#023c0d"),
	)

	EmeraldSea = gradient.New(
		colorful.Hex("#05386b"), colorful.Hex("#5cdb95"),
	)

	Bleem = gradient.New(
		colorful.Hex("#4284DB"), colorful.Hex("#29EAC4"),
	)

	CoffeeGold = gradient.New(
		colorful.Hex("#554023"), colorful.Hex("#c99846"),
	)

	Compass = gradient.New(
		colorful.Hex("#516b8b"), colorful.Hex("#056b3b"),
	)

	Andreuzzas = gradient.New(
		colorful.Hex("#D70652"), colorful.Hex("#FF025E"),
	)

	Moonwalker = gradient.New(
		colorful.Hex("#152331"), colorful.Hex("#000000"),
	)

	Whinehouse = gradient.New(
		colorful.Hex("#f7f7f7"), colorful.Hex("#b9a0a0"), colorful.Hex("#794747"), colorful.Hex("#4e2020"), colorful.Hex("#111111"),
	)

	HyperBlue = gradient.New(
		colorful.Hex("#59CDE9"), colorful.Hex("#0A2A88"),
	)

	Racker = gradient.New(
		colorful.Hex("#EB0000"), colorful.Hex("#95008A"), colorful.Hex("#3300FC"),
	)

	AftertheRain = gradient.New(
		colorful.Hex("#ff75c3"), colorful.Hex("#ffa647"), colorful.Hex("#ffe83f"), colorful.Hex("#9fff5b"), colorful.Hex("#70e2ff"), colorful.Hex("#cd93ff"),
	)

	NeonGreen = gradient.New(
		colorful.Hex("#81ff8a"), colorful.Hex("#64965e"),
	)

	DustyGrass = gradient.New(
		colorful.Hex("#d4fc79"), colorful.Hex("#96e6a1"),
	)

	VisualBlue = gradient.New(
		colorful.Hex("#003d4d"), colorful.Hex("#00c996"),
	)
)
